### ISSUE TITLE
Add Url Domain Whitelist

### ISSUE THREAD

**Issue by thegrb93** [Metastruct/pac3#24]
Can you guys add a command or file that allows adding/removing domains from a whitelist? Then message a player if their url is using a domain that isn't whitelisted. I don't like players using pac to sniff other player's ip addresses for ddos.

**Comment by LUModder** [comment]
Wait, this is a thing? You can sniff IP's with PAC?

**Comment by PotcFdk** [comment]
@LUModder, of course (!?)
Though, @thegrb93, are individuals really being DDoSed? That idea seems incredibly silly to me.
There are plenty of ways to get people's IP addresses. I don't see how making people's life harder by enforcing some kind of whitelist in PAC is reasonable.
You're trying to prevent IP address leakage, but what you're really doing is preventing players to use their own outfits (that is, unless they manage to contact the server owner and they agree to whitelist the host, which is troublesome).

**Comment by edunad** [comment]
I knew this would happen, when i released sprayurl people started bitching (no offense) about this :<

**Comment by notcake** [comment]
You could also get the server to make all http requests and pass the returned data back to clients. That way no functionality is lost, but it'd be a lot of work to get sounds and materials working that way. This kind of proxy solution isn't worth the effort to implement right now though.

**Comment by Python1320** [comment]
I'm eager to say add logging (accountability) and ban evil people with their URLs instead of whitelisting things. 

Another thing to do should be disabling externals by default. We could also add a whitelist that allows known safe urls and allows accepting/blocking other urls on demand.

Finally, making it so that outfits are only loaded when they are visible is a double edged sword, which may reduce the chance of getting everyone's IPs on the server but may allow seeing exactly who is who.

**Comment by suchipi** [comment]
I'm with PotcFdk here. I feel like this is a theoretical fix for a problem that doesn't actually exist (and, when it does, would be negligible). People that connect to any type of server kind of forfeit their right of IP address privacy by design. In this case, where the good are punished as well as the bad, it'd be best to take action when problems actually occur rather than punish/inconvenience 100% of users because there is a chance that 0.5% of them could extrapolate some data into something 'bad'. 

All this said, if a set of sane defaults and optional toggles using a set of Python's courses of action was applied, bad could be prevented without harming good.

**Comment by LUModder** [comment]
With my comment, I was being sarcastic a bit. I understand that it is possible to do that, but it's nothing that needs to be implemented. If you are having problems with stuff like this, I do feel sorry for you, but it just seems over concerning of something that really doesn't matter. You're gonna get DDoS'd at least once in your life, just accept it, yes it sucks, but it's rare for it to happen (at least in my case). I just think @thegrb93 is just over analyzing a lot of the "problems" with PAC, it's nothing personal, we all have moments where we over analyize stuff.

**Comment by thegrb93** [comment]
>Though, @thegrb93, are individuals really being DDoSed? 

Yes. People find it funny to target the server admins and take them off the server so they can minge around without consequence.

**Comment by LUModder** [comment]
@thegrb93 We need an example of this because I can't believe anything like this would really happen on highly populated servers, like Meta, Intertech, etc.

**Comment by thegrb93** [comment]
I don't have any ddos software/resources, but I can tell you if I did then I could easily walk next to an admin on a server, get his ip, and take him offline.

**Comment by thegrb93** [comment]
I can see in the logs when an admin gets taken offline and see who has worn a pac in the time frame.

**Comment by edunad** [comment]
@LUModder like i said above, it can happen.
People showed it and complained in sprayurl.

**Comment by PotcFdk** [comment]
You should keep in mind that, at least in my opinion, this is not a technical issue.
DDoSing people and/or servers is illegal. Don't cripple projects. Do something about it.
Oh, and @LUModder: no, we don't need any examples.

**Comment by thegrb93** [comment]
>Do something about it.

And what would you do?

**Comment by PotcFdk** [comment]
@thegrb93 Law enforcement.

**Comment by thegrb93** [comment]
How?

**Comment by Noiwex** [comment]
Ask your local police department.

**Comment by thegrb93** [comment]
Hilarious

**Comment by Noiwex** [comment]
Hilarious what, your local police department?

**Comment by LUModder** [comment]
@thegrb93 Seriously, if you have any DDoS issues, go report it to the police and not just post drama on the freaking PAC github.

**Comment by thegrb93** [comment]
That doesn't work and you know it. Stop joking around. I've added a white-list anyway. Have fun next time this exploit gets reported.

**Comment by LUModder** [comment]
1. This is closed
2. You're just putting more unneeded stuff on your server, you're overdoing this whole safety stuff. Stop it, no big name servers have this problem and I can see why.

**Comment by thegrb93** [comment]
no
